import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

// Real PostgreSQL engine, synthetic data only. Not a substitute for staging integration.
const db = new PGlite();
const user = '11111111-1111-4111-8111-111111111111';
const otherUser = '22222222-2222-4222-8222-222222222222';
const origin = 'https://xcjbjqndflhzmsxiasdb.supabase.co';
const product = { name: 'هاتف اختبار', description: 'وصف واضح طويل للهاتف', price: 100,
  category_id: 'phones', specifications: { model: 'Test' }, is_negotiable: false,
  condition: 'مستعمل', location: 'القاهرة - مدينة نصر', seller_id: otherUser, seller_name: 'forged',
  is_hidden: false, views_count: 99999 };
const id = () => crypto.randomUUID();
const paths = (productId: string, owner = user) => [0, 1].map(i => `products/${owner}/${productId}-${i}.jpg`);
async function upload(productId: string, owner = user) {
  for (const path of paths(productId, owner)) {
    await db.query(`INSERT INTO storage.objects(bucket_id,name,metadata) VALUES ('product-images',$1,'{"mimetype":"image/jpeg","size":200}')`, [path]);
  }
}
async function publish(productId: string, details = product, images = paths(productId)) {
  return db.query<{ result: { id: string; slug: string; image_count: number } }>(
    'SELECT public.publish_web_product($1::uuid, $2::jsonb, $3::text[]) AS result',
    [productId, JSON.stringify(details), images]);
}
async function count(productId: string, table = 'products') {
  const column = table === 'products' ? 'id' : 'product_id';
  return (await db.query<{ count: number }>(`SELECT count(*)::int AS count FROM public.${table} WHERE ${column}=$1`, [productId])).rows[0].count;
}

before(async () => {
  await db.exec(`
    CREATE ROLE authenticated NOLOGIN;
    CREATE ROLE anon NOLOGIN;
    CREATE SCHEMA auth;
    CREATE SCHEMA storage;
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
      $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE TABLE public.users(id uuid PRIMARY KEY, name text, profile_image_url text);
    CREATE TABLE public.categories(id text PRIMARY KEY, name text, is_active boolean);
    CREATE TABLE public.products(
      id uuid PRIMARY KEY, name text NOT NULL, description text NOT NULL,
      price double precision NOT NULL, category text NOT NULL,
      category_id text NOT NULL REFERENCES public.categories, specifications jsonb NOT NULL,
      seller_id uuid NOT NULL REFERENCES public.users, seller_name text NOT NULL, seller_avatar text,
      is_negotiable boolean, condition text, location text,
      slug text NOT NULL DEFAULT 'test-slug', is_hidden boolean DEFAULT true, views_count integer DEFAULT 0,
      ad_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE
    );
    CREATE TABLE public.product_images(
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      product_id uuid NOT NULL REFERENCES public.products ON DELETE CASCADE,
      user_id uuid NOT NULL REFERENCES public.users, image_url text NOT NULL,
      UNIQUE(product_id, image_url)
    );
    CREATE TABLE storage.objects(bucket_id text, name text, metadata jsonb, PRIMARY KEY(bucket_id,name));
    ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
    CREATE POLICY users_own ON public.users FOR SELECT TO authenticated USING (id=auth.uid());
    ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
    ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
    CREATE POLICY objects_read ON storage.objects FOR SELECT USING (bucket_id='product-images');
    CREATE POLICY objects_own_insert ON storage.objects FOR INSERT TO authenticated
      WITH CHECK (bucket_id='product-images' AND split_part(name,'/',2)=auth.uid()::text);
    INSERT INTO public.users VALUES ('${user}', 'Real Seller', null), ('${otherUser}', 'Other Seller', null);
    INSERT INTO public.categories VALUES ('phones', 'هواتف', true), ('inactive', 'inactive', false);
    GRANT USAGE ON SCHEMA public, auth, storage TO authenticated, anon;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public, storage TO authenticated;
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
  `);
  // Use the actual repository ownership policies rather than a mocked write check.
  const policies = readFileSync('../supabase/migrations/20260828080100_fix_rls_policies.sql', 'utf8').split('-- Comments')[0];
  await db.exec(policies);
  await db.exec(readFileSync('../supabase/setup/setup_product_slug.sql', 'utf8'));
  const categoryMigration = readFileSync('../supabase/migrations/20260821020000_canonical_product_categories.sql', 'utf8');
  const canonicalFunction = categoryMigration.match(/create or replace function public\.canonical_category_name[\s\S]*?\$\$;/)?.[0];
  const categoryTrigger = categoryMigration.slice(categoryMigration.indexOf('create or replace function public.sync_product_category_identity()'))
    .split('comment on column')[0];
  assert.ok(canonicalFunction);
  await db.exec(canonicalFunction + categoryTrigger);
  await db.exec(readFileSync('../supabase/migrations/20260902090000_atomic_web_product_publication.sql', 'utf8'));
  await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub = '${user}';`);
});
after(async () => { await db.close(); });

test('atomic success derives seller identity, ignores privileged fields and retains defaults', async () => {
  const productId = id(); await upload(productId);
  const result = (await publish(productId)).rows[0].result;
  assert.equal(result.id, productId);
  assert.equal(result.image_count, 2);
  assert.ok(result.slug.endsWith(productId));
  const specs = (await db.query<{ specifications: Record<string, string> }>('SELECT specifications FROM public.products WHERE id=$1', [productId])).rows[0].specifications;
  assert.equal(specs.category_name, 'هواتف');
  assert.equal(specs.category_id, 'phones');
  assert.equal(await count(productId), 1);
  assert.equal(await count(productId, 'product_images'), 2);
  const row = (await db.query<{ seller_id: string; seller_name: string; is_hidden: boolean; views_count: number; ad_number: number }>(
    'SELECT seller_id,seller_name,is_hidden,views_count,ad_number FROM public.products WHERE id=$1', [productId])).rows[0];
  assert.equal(row.seller_id, user);
  assert.equal(row.seller_name, 'Real Seller');
  assert.equal(row.is_hidden, true);
  assert.equal(row.views_count, 0);
  assert.ok(Number(row.ad_number) > 0);
  const url = (await db.query<{ image_url: string }>('SELECT image_url FROM public.product_images WHERE product_id=$1 LIMIT 1', [productId])).rows[0].image_url;
  assert.ok(url.startsWith(`${origin}/storage/v1/object/public/product-images/products/${user}/`));
});
test('repeated and queued calls with same ID create only one product and image set', async () => {
  const productId = id(); await upload(productId);
  const results = await Promise.all([publish(productId), publish(productId), publish(productId)]);
  assert.ok(results.every(r => r.rows[0].result.id === productId));
  assert.equal(await count(productId), 1);
  assert.equal(await count(productId, 'product_images'), 2);
});
test('missing storage upload fails before product insert', async () => {
  const productId = id();
  await assert.rejects(publish(productId), /Uploaded image missing/);
  assert.equal(await count(productId), 0);
});
test('deleted publication cannot be resurrected by an old retry', async () => {
  const productId = id(); await upload(productId); await publish(productId);
  await db.query('DELETE FROM public.products WHERE id=$1', [productId]);
  await assert.rejects(publish(productId), /no longer available/);
  assert.equal(await count(productId), 0);
  assert.equal((await db.query('SELECT 1 FROM public.web_product_publications WHERE product_id=$1', [productId])).rows.length, 1);
});
test('receipt cannot be reused with a changed payload or deleted by the caller', async () => {
  const productId = id(); await upload(productId); await publish(productId);
  await assert.rejects(publish(productId, { ...product, price: 200 }), /different data/);
  await assert.rejects(db.query('DELETE FROM public.web_product_publications WHERE product_id=$1', [productId]), /permission denied/);
  await db.exec(`SET request.jwt.claim.sub = '${otherUser}';`);
  try {
    assert.equal((await db.query('SELECT 1 FROM public.web_product_publications WHERE product_id=$1', [productId])).rows.length, 0);
  } finally { await db.exec(`SET request.jwt.claim.sub = '${user}';`); }
});
test('failing second image INSERT rolls back product and first image', async () => {
  const productId = id(); await upload(productId);
  await db.exec(`RESET ROLE;
    CREATE FUNCTION public.test_reject_second_image() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN IF new.image_url LIKE '%-1.jpg' THEN RAISE EXCEPTION 'injected image write failure'; END IF; RETURN new; END $$;
    CREATE TRIGGER test_image_failure BEFORE INSERT ON public.product_images FOR EACH ROW EXECUTE FUNCTION public.test_reject_second_image();
    SET ROLE authenticated;`);
  try {
    await assert.rejects(publish(productId), /injected image write failure/);
    assert.equal(await count(productId), 0);
    assert.equal(await count(productId, 'product_images'), 0);
    assert.equal((await db.query('SELECT 1 FROM public.web_product_publications WHERE product_id=$1', [productId])).rows.length, 0);
  } finally {
    await db.exec('RESET ROLE; DROP TRIGGER test_image_failure ON public.product_images; DROP FUNCTION public.test_reject_second_image(); SET ROLE authenticated;');
  }
});
test('image RLS rejection also rolls back the entire publication', async () => {
  const productId = id(); await upload(productId);
  await db.exec(`RESET ROLE; CREATE POLICY test_deny_image ON public.product_images AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK(false); SET ROLE authenticated;`);
  try {
    await assert.rejects(publish(productId), /row-level security/);
    assert.equal(await count(productId), 0);
    assert.equal(await count(productId, 'product_images'), 0);
  } finally {
    await db.exec('RESET ROLE; DROP POLICY test_deny_image ON public.product_images; SET ROLE authenticated;');
  }
});
test('unauthenticated and anonymous calls denied', async () => {
  await db.exec("SET request.jwt.claim.sub = '';");
  await assert.rejects(publish(id()), /Authentication required/);
  await db.exec(`SET request.jwt.claim.sub = '${user}'; RESET ROLE; SET ROLE anon;`);
  await assert.rejects(publish(id()), /permission denied for function/);
  await db.exec('RESET ROLE; SET ROLE authenticated;');
});
test('receipt write failure rolls back the product and all image links', async () => {
  const productId = id(); await upload(productId);
  await db.exec(`RESET ROLE; CREATE POLICY test_deny_receipt ON public.web_product_publications AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK(false); SET ROLE authenticated;`);
  try {
    await assert.rejects(publish(productId), /row-level security/);
    assert.equal(await count(productId), 0);
    assert.equal(await count(productId, 'product_images'), 0);
  } finally {
    await db.exec('RESET ROLE; DROP POLICY test_deny_receipt ON public.web_product_publications; SET ROLE authenticated;');
  }
});
test('cannot reuse someone else\'s product ID or storage path', async () => {
  const productId = id(); await upload(productId); await publish(productId);
  await db.exec(`SET request.jwt.claim.sub = '${otherUser}';`);
  try {
    await assert.rejects(publish(productId), /Invalid image ownership/);
    await upload(productId, otherUser);
    await assert.rejects(publish(productId, product, paths(productId, otherUser)), /Product ID unavailable|duplicate key/);
  } finally { await db.exec(`SET request.jwt.claim.sub = '${user}';`); }
  assert.equal(await count(productId), 1);
});
test('reject duplicate/null/path traversal/too many/no image paths', async () => {
  const productId = id(); await upload(productId);
  for (const images of [[], Array(5).fill(paths(productId)[0]), [paths(productId)[0], paths(productId)[0]],
    [`products/${user}/../other.jpg`], [null] as unknown as string[]]) {
    await assert.rejects(publish(productId, product, images));
  }
  assert.equal(await count(productId), 0);
});
test('reject invalid price/category/description without partial records', async () => {
  const productId = id(); await upload(productId);
  for (const details of [{ ...product, price: -1 }, { ...product, price: null }, { ...product, price: 'NaN' },
    { ...product, price: 'Infinity' }, { ...product, category_id: 'inactive' }, { ...product, description: 'short' }]) {
    await assert.rejects(publish(productId, details as typeof product));
  }
  assert.equal(await count(productId), 0);
});
test('non-image or oversized storage metadata cannot become a listing image', async () => {
  const productId = id(); await upload(productId);
  await db.exec('RESET ROLE;');
  await db.query(`UPDATE storage.objects SET metadata='{"mimetype":"image/svg+xml","size":200}' WHERE name=$1`, [paths(productId)[0]]);
  await db.exec('SET ROLE authenticated;');
  await assert.rejects(publish(productId), /Uploaded image missing or invalid/);
  assert.equal(await count(productId), 0);
});
